### ISSUE TITLE
withAsync appears to not cancel the inner async action

### ISSUE THREAD

**Issue by qwbarch** [tek/polysemy-conc#1]
Here's an example program:
```haskell
main :: IO ()
main = do
  runFinal @IO
    . embedToFinal @IO
    . asyncToIOFinal
    . resourceToIOFinal
    . interpretRace
    $ withAsync (forever . embed $ putStrLn "Hello world!") (const $ pure ())
  void getLine
```
I'd expect this to to get cancelled since the outer effect does nothing, but this indefinitely prints out "Hello world!".

**Comment by qwbarch** [comment]
I believe this issue is due to ``bracket`` not catching async exceptions.
This is my first time dealing with async exceptions, sorry if I make any obvious mistakes!

My first thought to solve this is to use ``withLowerToIO`` and ``withAsync`` from the ``async`` package itself.  
While this sounds foolproof, this creates an extra thread on each of our custom ``withAsync`` calls.  
To avoid this, I tried two attempts (which unfortunately failed).

My first attempt on solving this was to copy [bracket](https://hackage.haskell.org/package/unliftio-0.2.21.0/docs/UnliftIO-Exception.html#v:bracket) from the ``unliftio`` package:
```haskell
bracket :: Members [Mask resource, UninterruptipleMask resource, Critical, Embed IO] r => Sem r a -> (a -> Sem r b) -> (a -> Sem r c) -> Sem r c
bracket before after between = mask $ do
  beforeResult <- raise before
  betweenResult <- catch @_ @SomeException . restore . raise $ between beforeResult
  case betweenResult of
    Left exception -> do
      catch @_ @SomeException . raise . uninterruptibleMask . raise $ after beforeResult
      embed $ throwIO exception
    Right result -> do
      raise . uninterruptibleMask . raise $ after beforeResult
      return result
```
Unfortunately, I misunderstood the documentation in ``unliftio``, thinking this would catch async exceptions.
Using the bracket function as defined above still doesn't cancel the async effect properly.

My next thought was to simply copy over the actual [withAsync](https://hackage.haskell.org/package/async-2.2.4/docs/src/Control.Concurrent.Async.html#withAsyncUsing) implementation.
Unfortunately, the ``Async`` effect's constructor isn't exposed, so I had to scrap this attempt as well.

Since the other two attempts failed, his brings me back to ``withLowerToIO``.  
Does this even sound like a good idea? Are there any obvious gotchas with this approach?
I'll write a PR for this tomorrow if I get the green light to continue!

**Comment by googleson78** [comment]
There's an issue (apart from spawning an extra thread) with this approach in that `withLowerToIO` is disliked by (most?) of the polysemy team, and I recall some plans to remove it entirely for v2. (see https://github.com/polysemy-research/polysemy/pull/422/commits/45786008db6fe0e40a191070cdc299bba91db816)

**Comment by tek** [comment]
I think this has an entirely different cause, since this:
```haskell
        withAsync (forever (embed (putStrLn "yello" *> threadDelay 1))) \ _ -> do
          embed (putStrLn "main")
```
only prints one "yello". I'll investigate later.

**Comment by tek** [comment]
ok, the variant I posted works because `threadDelay` is a blocking, and therefore interruptible, operation. I'd say your assessment is correct. I'll look into creating a proper implementation for this

**Comment by tek** [comment]
alright, a really simple alternative is:

```haskell
  handle <- async mb
  finally (use handle) (cancel handle)
```

not sure what the advantage of `Control.Concurrent.Async.withAsync`'s implementation is, the comment says "The bracket version works, but is slow.". So I think I'll keep it simple for now and just use this.

**Comment by tek** [comment]
published a new version

**Comment by qwbarch** [comment]
Thanks for the quick fix!
