### ISSUE TITLE
 Ambiguous occurrence ‘empty’

### ISSUE THREAD

**Issue by teto** [tek/polysemy-conc#3]
Trying the latest release 0.10.0.0 with a nix triggers

```
note: keeping build directory '/tmp/nix-build-polysemy-conc-0.10.0.0.drv-0'
error: builder for '/nix/store/ydf5gqjwpnbchnw1d2gcbhvqxy2r9z5a-polysemy-conc-0.10.0.0.drv' failed with exit code 1;
       last 30 log lines:
       >   | ^
       >
       > lib/Polysemy/Conc/Effect/SyncRead.hs:1:1: error:
       >     Ambiguous occurrence ‘empty’
       >     It could refer to
       >        either ‘Prelude.empty’,
       >               imported from ‘Prelude’ at lib/Polysemy/Conc/Effect/SyncRead.hs:4:8-36
       >               (and originally defined in ‘GHC.Base’)
       >            or ‘Polysemy.Conc.Effect.SyncRead.empty’,
       >               defined at lib/Polysemy/Conc/Effect/SyncRead.hs:19:1
       >   |
```

I suspect the `makeSem ''SyncRead` tries to convert `Empty` into `empty` ?

**Comment by tek** [comment]
that is very curious…is there something unusual about your project that might trigger this?
I don't get that error with any of the GHC versions in the flake.
can you post the nixpkgs commit?

**Comment by teto** [comment]
forgot to precise it is with ghc 9.4. It's in a project with many dependency overrides so it's possible it's specific but the error seem self contained. How can I get a development shell with the flake of this repo ? I would like to bump ghc to 9.4 and check if it happens then as well.

**Comment by tek** [comment]
ah, interesting. I haven't attempted 9.4 yet.
You can try setting `devGhc.compiler = "ghc942"` in `flake.nix`, then `nix develop` and `nix build` should use 9.4.

I just updated the flake to ensure 9.4 is available, so make sure to pull.
If you're gonna try adding overrides it's probably helpful to look at the docs at https://git.tryp.io/tek/hix :)

**Comment by teto** [comment]
I compiled with ghc94 and cabal just fine so I double checked the logs  and there was before sokmething like
```
       > lib/Polysemy/Conc/Effect/SyncRead.hs:1:1: error:
       >     Can't add documentation to empty as it isn't inside the current module
       >   |
       > 1 | {-# options_haddock prune #-}
       >   | ^
```
if I add `dontHaddock` in front of the nix derivation then it compiles fine. I then saw the same issue with polysemy-log (with the same fix). 
What's weird to me is that `cabal haddock --allow-newer` built just fine so I wonder if nix doesn't do anything extra that triggers the issue.

**Comment by tek** [comment]
that's bananas. I'll try to investigate!

**Comment by tek** [comment]
ohhh I remember now that we have that TH documentation feature in polysemy that's only available in 9.2 and newer. Basically it copies the docstrings from the GADT constructors to the smart constructors when using `makeSem`. So maybe the TH feature that allows this has changed in 9.4. I'll have a look.

**Comment by tek** [comment]
as a quick workaround, I've hidden `empty` from Prelude. can you check whether that prevents the issue?

**Comment by tek** [comment]
ah damn :)

**Comment by teto** [comment]
It fixed the issue <3 !

**Comment by tek** [comment]
yay! I'll push a release
